name: Deploy LeoFinder

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: cd server && npm ci
    
    - name: Build frontend
      run: npm run build
      env:
        VITE_API_BASE_URL: https://leofinder-backend.onrender.com/api
    
    - name: Build backend
      run: cd server && npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          dist/
          server/dist/
          
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to Netlify
      run: echo "Frontend will auto-deploy via Netlify GitHub integration"
    
    - name: Deploy Backend
      run: echo "Backend deploys automatically via Render GitHub integration"